#!/bin/bash

res=0

setup() {
    set -e
    # Install python3 and plumbum
    sudo yum install python3 -y >/dev/null
    pip3 install --user plumbum python-consul >/dev/null

    # Build patroni image
    docker-compose -f $BASE/files/dc-patroni.yml build >/dev/null

    export TOUT_DIR=$(mktemp -d /tmp/tout.XXXXXX)
    set +e
}

run_test() {
    local TEST_NAME="$1"
    echo "Running: $TEST_NAME"
    local TST_DIR="$TOUT_DIR/$TEST_NAME"
    mkdir -p "$TST_DIR"
    ARTIFACTS_DIR="$TST_DIR" "./acceptance/${TEST_NAME}_acceptance/test.py" setup &&\
    ARTIFACTS_DIR="$TST_DIR" "./acceptance/${TEST_NAME}_acceptance/test.py" run
    ARTIFACTS_DIR="$TST_DIR" "./acceptance/${TEST_NAME}_acceptance/test.py" teardown
}

run_tests() {
    export PYTHONPATH=acceptance/:.
    for test in "leader_failure" "follower_failure"; do
        run_test "$test"
        res=$((res+$?))
    done
    if [ $res -eq 0 ]; then
        echo "All tests successful"
    else
        echo "$res tests failed"
    fi
}

collect_artifacts() {
    ARTIFACTS="patroni.${BUILDKITE_ORGANIZATION_SLUG}.${BUILDKITE_BUILD_NUMBER}"
    mkdir -p artifacts.out
    tar -caf "artifacts.out/$ARTIFACTS.tar.gz" "$TOUT_DIR"
}

setup
run_tests
collect_artifacts

exit $res
