#!/bin/bash

set -e

# Install python3 and plumbum
sudo yum install python3 -y >/dev/null
pip3 install --user plumbum >/dev/null

# Build patroni image
docker-compose -f $BASE/files/dc-acceptance.yml build >/dev/null

# Run acceptance tests
echo "do some tests now"
