- label: Run patroni unit tests, linting and acceptance
  command:
    - $BASE/scripts/patroni
  plugins:
    - docker-compose#v3.0.0:
        config: $BASE/files/dc-patroni.yml
        run: patroni
  retry:
    automatic:
      exit_status: 255
  timeout_in_minutes: 10
- label: Run anapaya acceptance tests
  command: $BASE/scripts/acceptance
  retry:
    automatic:
      exit_status: 255
  timeout_in_minutes: 10
